In [3]:
import numpy as np

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:

# The memory size in Bytes required by an rectangular array is (# of rows)*(# of cols)*(size of one element).


In [6]:
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (2787590163.py, line 1)

In [7]:
Z= np.zeros(10)
Z[4]= 1
print (Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
Z=np.arange(10,15)
print (Z)

[10 11 12 13 14]


In [9]:
Z = np.arange(10,50)
Z= Z[::-1]
print (Z)
# 8

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [10]:
Z = np.arange(9).reshape(3,3)
print (Z)
# 9

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)
# 10

(array([0, 1, 4]),)


In [12]:
Z= np.eye(3)
print (Z)
# 11

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
Z = np.random.uniform((3,3,3))
print (Z)
# 12

[2.91697628 2.2454985  1.14542778]


In [14]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
# 13

0.010697551768011127 0.9912193060154255


In [29]:
Z = np.random.random(30)
m = Z.mean()
print (m)
# 14

0.4811036757264031


In [30]:
Z = np.ones((10,10))
Z[1:-1,1:-1]=0
