In [3]:
import numpy as np

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:

# The memory size in Bytes required by an rectangular array is (# of rows)*(# of cols)*(size of one element).


In [6]:
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (2787590163.py, line 1)

In [7]:
Z= np.zeros(10)
Z[4]= 1
print (Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
Z=np.arange(10,15)
print (Z)

[10 11 12 13 14]


In [9]:
Z = np.arange(10,50)
Z= Z[::-1]
print (Z)
# 8

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [10]:
Z = np.arange(9).reshape(3,3)
print (Z)
# 9

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)
# 10

(array([0, 1, 4]),)


In [12]:
Z= np.eye(3)
print (Z)
# 11

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
Z = np.random.uniform((3,3,3))
print (Z)
# 12

[2.91697628 2.2454985  1.14542778]


In [14]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
# 13

0.010697551768011127 0.9912193060154255


In [29]:
Z = np.random.random(30)
m = Z.mean()
print (m)
# 14

0.4811036757264031


In [30]:
Z = np.ones((10,10))
Z[1:-1,1:-1]=0


In [ ]:
# use np.pad constant_values = 0

In [31]:
# nan
# False
# False
# nan
# False
# 17

In [33]:
Z = np.diag([1, 2, 3, 4, 7])
print (Z)
# 18

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 7]]


In [42]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)
# 19

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [43]:
print (np.unravel_index(100, (6,7,8)))
# 20

(1, 5, 4)


In [44]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)
# 21

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [45]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)
# 22

[[0.44846829 0.44385989 0.67379155 0.82986727 0.33559544]
 [0.16222142 0.83101256 0.63833101 0.         0.33722307]
 [0.8748786  1.         0.95924953 0.07288862 0.91007084]
 [0.10514149 0.83530527 0.92817887 0.73262191 0.44779236]
 [0.17903851 0.48958961 0.24130125 0.85237894 0.60511021]]


In [51]:
array = np.array([2, 4], dtype = np.int16)
print(array.dtype)
# 23

int16


In [52]:
Z= np.dot(np.ones((5,3)), np.ones((3,2)))
print (Z)
# 24

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
